data:extend({
    {
        type="item",
        name="logistics-power-junction",
        icon="__logistics-pipes__/graphics/icons/misc/power-junction.png",
        icon_size=64,
        stack_size=64,
        place_result="logistics-power-junction"
    }
})